language: c

sudo: required
dist: bionic

matrix:
    include:
        - name: 32 bit
          install: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install libbenchmark-dev:i386 zlib1g-dev:i386 g++-multilib clang
          before_script: env CXX=clang++ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_32BIT=on .
        - name: 64 bit
          install: sudo apt-get install libbenchmark-dev zlib1g-dev g++ clang
          before_script: env CXX=clang++ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_32BIT=off .

script:
    - cmake --build . -j 2
    - LD_PRELOAD=libSegFault.so ./psa --benchmark_min_time=0.9 dome-roof-on_zoom0.sv6.psa
