name: C/C++ CI

on: [push]

jobs:
  build-x86:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install packages
      run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install zlib1g-dev:i386 libicu-dev:i386 g++-multilib clang
    - name: install Google benchmark
      run: git clone https://github.com/google/benchmark && cd benchmark && CFLAGS=-m32 LDFLAGS=-m32 cmake . -DCMAKE_BUILD_TYPE=relwithdebinfo -DBUILD_SHARED_LIBS=ON -DBENCHMARK_ENABLE_GTEST_TESTS=OFF -DCMAKE_CXX_FLAGS="-m32" -DCMAKE_INSTALL_LIBDIR=lib32 && sudo make install -j2 && cd ..
    - name: configure
      run: mkdir build && cd build && env CXX=clang++ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_32BIT=on ..
    - name: build
      run: cmake --build build
    - name: Upload artifacts (CI)
      uses: actions/upload-artifact@v1
      with:
        name: "psa-lin32"
        path: build
    - name: benchmark
      run: cd build && LD_PRELOAD=libSegFault.so ./psa --benchmark_min_time=0.9 ../dome-roof-on_zoom0.sv6.psa

  build-x86_64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install packages
      run: sudo apt-get update && sudo apt-get install zlib1g-dev g++ clang
    - name: install Google benchmark
      run: git clone https://github.com/google/benchmark && cd benchmark && cmake . -DCMAKE_BUILD_TYPE=relwithdebinfo -DBUILD_SHARED_LIBS=ON -DBENCHMARK_ENABLE_GTEST_TESTS=OFF && sudo make install -j2 && cd ..
    - name: configure
      run: mkdir build && cd build && env CXX=clang++ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_32BIT=off ..
    - name: build
      run: cmake --build build
    - name: Upload artifacts (CI)
      uses: actions/upload-artifact@v1
      with:
        name: "psa-lin64"
        path: build
    - name: benchmark
      run: cd build && LD_PRELOAD=libSegFault.so LD_LIBRARY_PATH=/usr/local/lib/ ./psa --benchmark_min_time=0.9 ../dome-roof-on_zoom0.sv6.psa

  build-x86_64-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: install vcpkg
      run: vcpkg install benchmark:x64-windows zlib:x64-windows
    - name: cmake configure
      run: cmake . -A x64 -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows
    - name: build
      run: cmake --build . --config Release
    - name: Upload artifacts (CI)
      uses: actions/upload-artifact@v1
      with:
        name: "psa-win64"
        path: Release
    - name: benchmark
      run: Release/psa --benchmark_min_time=0.9 dome-roof-on_zoom0.sv6.psa
